manifest:

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: eyelash_corne
      url-base: https://github.com/a741725193
    - name: nanda-irjayandi
      url-base: https://github.com/nanda-irjayandi

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-new_corne
      remote: eyelash_corne
      revision: main
    - name: zmk-helpers # from urob
      remote: nanda-irjayandi
      revision: main
      
  self:
    path: config
